services:
- postgresql
addons:
  postgresql: '9.6'
language: ruby
rvm:
- 2.7.1
script:
- bundle exec rails db:reset db:setup db:migrate RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key: KDmBjiZeoUJ4v3yHwSkD0gK6JKwd8hTt4vJb5R6tejxgYMbTv9xugWx6gefBm1/LYa4kC8BQFgGpYQLERfu36O4+pCW8bR9sXs9awC8X3q6T9dbpb1ObmiS62A213eevzFdcr01ePhpB0t+gMrb6RGYlQGpNdOtuQ8DkMlNyrFpjXNd9H4ZnBgehtuSbO2I0YJripXXwlNH23khhVOZWbAIWchexTnl3S3QBK7oMmyV1U5ygrZogtXa0N8vZx1QYQ0ONST05o6PhIJE/q+7zMHcD7LkcQaFXC/GdBeycA3dWlyC5AvMbF+8Nev5Cl6rGfF7rd9BZ8GOvZwGINiDpQ0evqbcxurKXkLg4fwfQMZvZGp7NHTv5T/tRDrfN9KE983L07bLCkCSsSXbe6HkWoV/GHjj5xOle5mM5PnS2It7VcSQUP+ZXsjyYxUK6HtxDrT2s0oWFCotJwOaMhTOarA+xbPcqEE0MO4jO6gYXeOiSKAjKNOMcDU1U5uYuDeglMPBxrrajWPELETxlX8tfMklg1O0BQ2RbS9gOmz4TXFwgVe2ZuzG2kARfBoHUatIj2gCr+sYTqU77y7flHV9PN/Siq3Tx7VDifZ36cKL06+1GTOCL6JOjHKmd7dmXvc8a1GMIbPafa6Cqe+irUQEvcjXUSYrIsKCu7GyrDSYtjXs=
  skip_cleanup: true
  app:
    main: tzetzes
  run: rake db:migrate
