services:
- postgresql
addons:
  postgresql: '9.6'
language: ruby
rvm:
- 2.7.1
script:
- bundle exec rails db:reset db:setup db:migrate RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: EThM4t6vNB/c0wfCKDfevObxGhPFsHksixg+TN/V/wAyzDrtyD5f0NZFjnkGdynzIfKCwAARQJ0EWG7n4QUCtdF7GkKBTsf/NOFhKkOEKvA9g3m6P0VLp7mTBSQI3m/L8VE8/bEob42nq0gOI0xkOCKYvPBp3AjthL34oEZquKKokdZYthZtp8kpG+a/+MUWnGPzg8dvuSQRubD5vQ+dAueYHW+7aqgRNYieyfkTf/G9QX+cCgU62JcZ0BmfKfll3dyo8S+l+HbHJnyD8k0zHlOHJ9F2fv+IiUtGP51I1Fy+FVIyXPg16wYU+SjdZfD4S33NJADlrObTKhUuIVz8USoClizrNd3bSGOKmFfmKQfzAHKSv495f/KvJoM7v6i/ty8ZvyKAar66XlYE8W1oPpcZpZFm0cNib6B3t/sKC9NtZIIpq1MDIqdY60alFaL3QOz32wSByaVHSQ3M3tFnSg1rPePZE+KezuyweboNT5jGho5NVl4OKfXNpkGHF0M5fMqiWTvw0kEfZMP+Ag6PH+9ankyzlf+lKq2EMmMOWBffZ1Yf0OAR+u452xd5NLD5+FXi2HTERUXEQ0TpIp+9MIkQKe+AhdsZFSMAIWB/bTvXiEhInCRYiHdrOScWWxrraejv4REy9ikMF23HfEHtJ8hmgc1wXfULH0g4SIK976Y=
  skip_cleanup: true
  app:
    main: tzetzes
  run: rake db:migrate
