version: 2
jobs:
    build:
        working_directory: ~/tzetzes-mps
        docker:
          - image: circleci/ruby:2.4.1
            environment:
              PGHOST: localhost
              PGUSER: tzetzes-mps
              RAILS_ENV: test
          - image: postgres:9.5
            environment:
              POSTGRES_USER: tzetzes-mps
              POSTGRES_DB: tzetzes-mps_test
              POSTGRES_PASSWORD: "circle_ci_postgres"
              # POSTGRES_HOST_AUTH_METHOD: trust
        steps:
            - checkout
            # Bundle install dependencies
            - run: bundle install --path vendor/bundle
            # environment
            - run: cp .sample.env .env
            # DB
            - run: bundle exec rake db:setup
            # tests
            - run: bundle exec rspec 
