version: 2.7
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    executor: docker
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - bundle-install
